name: "Deploy Snapshots"
on:
  push:
    branches:
      - main
env:
  MAVEN_ARGS: "-B -ntp -U"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy"
    steps:
      - uses: actions/checkout@v5
      - name: "Set up Maven Central Repository"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: "Deploy snapshots"
        run: mvn -Prelease deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
  jdk:
    needs: deploy
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
    runs-on: ubuntu-latest
    name: "Verify snapshots with JDK ${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v5
      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: maven
      - name: "Test"
        run: cd instancio-tests && mvn verify
  junit:
    needs: deploy
    strategy:
      matrix:
        junit: [ 6.0.1 ]
    runs-on: ubuntu-latest
    name: "Verify snapshots with Junit ${{ matrix.junit }}"
    steps:
      - uses: actions/checkout@v5
      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
          cache: maven
      - name: "Test"
        run: cd instancio-tests && mvn verify -pl :instancio-junit-tests -am -Dversion.junit=${{ matrix.junit }}
  guava:
    needs: deploy
    strategy:
      matrix:
        guava: [ 23.6.1-jre, 24.1.1-jre, 25.1-jre, 26.0-jre, 27.1-jre, 28.2-jre, 29.0-jre, 30.1.1-jre, 31.1-jre, 32.1.3-jre, 33.4.8-jre ]
    runs-on: ubuntu-latest
    name: "Verify snapshots with Guava ${{ matrix.guava }}"
    steps:
      - uses: actions/checkout@v5
      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
          cache: maven
      - name: "Test"
        run: cd instancio-tests && mvn verify -pl :instancio-guava-tests,:jpms-guava-tests -am -Dversion.guava=${{ matrix.guava }}
  experimental:
    needs: deploy
    runs-on: ubuntu-latest
    name: "Verify snapshots with early access JDK"
    steps:
      - uses: actions/checkout@v5
      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 26-ea
          cache: maven
      - name: "Test"
        run: cd instancio-tests && mvn verify
